### ISSUE TITLE
Virtual CPU

### ISSUE THREAD

**Issue by adam4813** [trillek-team/tec#10]

**Comment by Zardoz89** [comment]
trillek-vcomputer module it's working alone very well. I think that we need to fo the wrapper components and should work on the engine.

**Comment by adam4813** [comment]
Yeah most of the old engine code can be adapted as it was fairly encapsulated.

**Comment by adam4813** [comment]
Once the wire system is in place this will be merged and closed.

**Comment by milesrout** [comment]
@adam4813 should this be closed?

**Comment by Zardoz89** [comment]
I think that we should. We have it working, but don't does anything against the world.
