### ISSUE TITLE
Multisample Antialiasing + Mipmapping

### ISSUE THREAD

**Issue by milesrout** [trillek-team/tec#100]
These would make the floor look _much_ nicer.

**Comment by milesrout** [comment]
e.g.
```cpp
GLFWmonitor* primary = glfwGetPrimaryMonitor();
const GLFWvidmode* mode = glfwGetVideoMode(monitor);
glfwWindowHint(GLFW_SAMPLES, 4);
GLFWwindow *window = glfwCreateWindow(mode->width, mode->height, "TEC", monitor, NULL);
```

**Comment by milesrout** [comment]
We can generate mipmaps with `glGenerateMipMaps`, which was added in OpenGL 3. I'm not sure if these would be as good as mipmaps generated by hand, but they'll be good enough for most textures, I'm sure. 

(I believe that hand-generated mipmaps can ensure that you don't lose particularly small details when scaled down, like hard white pixels used to indicate a 'sparkle').

**Comment by adam4813** [comment]
Yeah we can certainly use auto mipmaps for now though we don't have much
textures. What is really need for the floor is anisotropic filtering.

**Comment by milesrout** [comment]
I was going to tag this good-for-beginners but actually I think it requires quite a few deep changes to separate out framebuffer vs. window sizes which is necessary both for this and for proper retina display support IIRC.

**Comment by adam4813** [comment]
Moving this to done as I have made changes in this direction.
