### ISSUE TITLE
Issues with OpenGL on some computers

### ISSUE THREAD

**Issue by jmf** [trillek-team/tec#101]
There seem to be errors like this one on some GPUs:

```
ASSERT: Scalar FS validation failed!
load_payload(8) vgrf11:UD, (null):UD(null):UD(null):UD, vgrf6:F
../../../../../../src/mesa/drivers/dri/i965/brw_fs_validate.cpp:53: inst->src[i].reg_offset + inst->regs_read(i) <= (int)alloc.sizes[inst->src[i].nr]
Aborted (core dumped)
```

valarionch on reddit linked this one as possible solution:
https://www.opengl.org/discussion_boards/showthread.php/149004-glDrawBuffer(-GL_NONE-)-expected-behaviour

**Comment by milesrout** [comment]
This might be related:

https://bugs.freedesktop.org/show_bug.cgi?id=94444

**Comment by jmf** [comment]
Yes, I also linked that on reddit.
https://www.reddit.com/r/trillek/comments/4mgh0f/trillek_v010_release/d3vp565

**Comment by milesrout** [comment]
@jmf you can definitely reproduce this, given you reported it

**Comment by jmf** [comment]
The bug looks like it is a bug in the Intel driver.
Since it works on all my other computers, which don't use Intel GPUs, that hypothesis is likely.

**Comment by adam4813** [comment]
@jmf are you on linux as it seemed it was fixed on MESA 13?

**Comment by adam4813** [comment]
It is possible this is fixed with a change to how the context was created that wasn't actually giving expected results and had a broken version check.

**Comment by jmf** [comment]
I tried to confirm the error but trillek only builds on Linux with heavy modifications and segfaults at startup. It would be best to keep this issue open and to get trillek to run again in order to allow re-evaluation of the OpenGL issue.

**Comment by adam4813** [comment]
@jmf the build is now fixed in the improve build PR, I know it's a long shot but can you retest this again once it is merged?

**Comment by milesrout** [comment]
definitely needs to be fixed before the next release if it hasn't been already

**Comment by milesrout** [comment]
@jmf Can you reproduce this now?

**Comment by adam4813** [comment]
@jmf Can you pull down a release build and see if this is still relevant? I will be closing this issue at the end of Feb 2021 if I don't hear back.
