### ISSUE TITLE
Packaged binary builds

### ISSUE THREAD

**Issue by danielekmann** [trillek-team/tec#102]
`.deb`, `.rpm` etc instead of binaries in `.tar.gz`'s.

**Comment by jmf** [comment]
Tarballs (.tar.gz and .tar.xz) are the usual, platform-agnostic distribution method for packages that aren't meant to be installed. 
And I would not recommend installing Trillek in system directories since it is in early development, sometimes unstable and there is currently no advantage in installing it, over just using it locally.

**Comment by milesrout** [comment]
Good package managers allow you to install packages locally.

**Comment by jmf** [comment]
I know no package manager that does that by default. 
It is unusual to install packages locally, that's the reason why paths inside of them match the file system as seen from /.
There is no single advantage in making packages for all the dozens of package managers when tarballs work just as well and only have to be made for all distros.

**Comment by rodneyrod** [comment]
Also, just letting someone know, the binary builds don't work on Arch based distros since the Lua5.2 library is called something different there than on Debian derived distros.

If someone could fix that issue, or put together an AUR as an alternative, it would be greatly appreciated.

**Comment by milesrout** [comment]
@jmf Then you don't know any good package managers. The fact remains that good package managers allow you to install packages locally.

**Comment by jmf** [comment]
@rodneyrod That's just a naming difference, it is binary compatible though. You can solve it by creating a symlink with the name of the missing library, pointing to the existing Lua lib.
That should work as a temporary solution, if you want to use the binary build instead of building it yourself.

**Comment by rodneyrod** [comment]
already did that a while back, working fine now

**Comment by milesrout** [comment]
Okay so coming back to this I think that we should try to get binary builds for at least Debian, Fedora and Ubuntu (and of course Windows) by the next release. 

I will set up a VM for each when I get home and I'll try to work out the exact build and packaging steps on each. From what I remember Semaphore is capable of uploading binary packages to the GitHub Releases page. 

Having nightly builds would be a good "stretch goal".

**Comment by adam4813** [comment]
I will work on appveyor tomorrow to get Windows builds.
