### ISSUE TITLE
ProtoLoadEntity file not found.

### ISSUE THREAD

**Issue by Chase-san** [trillek-team/tec#103]
With the release v0.10. I get the error "ERROR! [ProtoLoadEntity] Error opening file. Can't find it". This error just after "Initializing script system...". I did install OpenAL to no benefit, as this error occurs long after initializing the sound.

At this point I also get a large man with a sword waving around what appears to be a lantern in a loop.

**Comment by adam4813** [comment]
You can safely ignore the file not found as your copy of the game might be
trying to load a file that isn't needed anymore and got fixed later in the
code.

What you see sounds correct.

**Comment by Vaelon1** [comment]
Forgive my ignorance, but does this mean I need to download a different version of the game? I haven't been able to find a more recent copy. Is there a way to make this one work?

**Comment by adam4813** [comment]
It should be safe to ignore if the world has "things" in it.

I have been very busy in my real life and haven't had a chance to work on
trillek in months, but I will see if I can iron out this issue this coming
weekend fully.
