### ISSUE TITLE
RenderSystem::RenderSystem() segfault

### ISSUE THREAD

**Issue by milesrout** [trillek-team/tec#122]
RenderSystem::RenderSystem() segfaults on my computer. The reason is that GLEW doesn't understand Core contexts properly in old versions, so it doesn't load extensions. That means glGenFramebuffers (among other functions) is NULL and causes a segfault when it is called in GBuffer's constructor.

GLEW is outdated garbage and we should replace it with GLAD.

In the meantime, `glewExperimental = GL_TRUE;` before glewInit() fixes the problem.

**Comment by adam4813** [comment]
Or update glew? Glew 2.0 fixes this.

**Comment by milesrout** [comment]
that could work
