### ISSUE TITLE
Place-able entity list (GUI)

### ISSUE THREAD

**Issue by adam4813** [trillek-team/tec#125]
A GUI list that contains a predefined list of place-able entities. The currently selected place-able needs to be query-able.

**Comment by adam4813** [comment]
Minecraft-like hotbar?

**Comment by milesrout** [comment]
I'm not sure this would be easy for a beginner.

**Comment by adam4813** [comment]
Agreed, this requires familiarity with Dear ImGui and the underlying system's that would include player inventory etc that aren't in place yet.

**Comment by adam4813** [comment]
#176 is all about the infrastructure to support a GUI. This ticket can be moved to the new release if time doesn't permit.
