### ISSUE TITLE
Build failure with g++ 7.3.0

### ISSUE THREAD

**Issue by danielabbott** [trillek-team/tec#126]
tec/deps/spdlog/include/spdlog/details/format.h:2166:24: error: expected unqualified-id before numeric constant
         const unsigned CHAR_WIDTH = 1;

Issue is caused by a naming conflict with CHAR_WIDTH in limits.h

Fixed here: https://github.com/fmtlib/fmt/commit/abbefd71666055daac9e14e78262620f9e845850

**Comment by fahlmant** [comment]
I replaced the format.h file with the one linked at abbefd7, and while it fixed that error, the new file gave me the following:

```
git/tec/deps/spdlog/include/spdlog/details/format.h:1178:21: error: static assertion failed: Cannot format argument. To enable the use of ostream operator<< include fmt/ostream.h. Otherwise provide an overload of format_arg.
   FMT_STATIC_ASSERT(False<T>::value,
```

**Comment by fahlmant** [comment]
@adam4813 +1 to that. Any idea on timeframe? (also, I see you aren't on IRC, we could discuss this there :) )

**Comment by adam4813** [comment]
@fahlmant this should be resolved now with the latest PR, at least it builds on gcc 7 and visual studio 2019.
