### ISSUE TITLE
Window resizing enhancements

### ISSUE THREAD

**Issue by adam4813** [trillek-team/tec#13]
Window resizing needs min/max size checking and to make it ratio based.

**Comment by milesrout** [comment]
Seems to me like this should be stored in a configuration file somewhere. As as sidenote I think that we should be loading configuration files just using lua, e.g. `config.lua` with:

```lua
width = 1920
height = 1200
```

And we should probably just default to full screen mode:

```cpp
GLFWmonitor* primary = glfwGetPrimaryMonitor();
const GLFWvidmode* mode = glfwGetVideoMode(monitor);
GLFWwindow *window = glfwCreateWindow(mode->width, mode->height, "TEC", monitor, NULL);
```

**Comment by milesrout** [comment]
GLFW 3.2 adds `glfwSetWindowSizeLimits` and `glfwSetWindowAspectRatio` "for setting absolute and relative window size limits", which is relevant.

**Comment by adam4813** [comment]
Perfect the issue has resolved itself.

**Comment by jmf** [comment]
Can this issue be closed yet?

**Comment by milesrout** [comment]
No
