### ISSUE TITLE
Build fail with VCPKG's spdlog

### ISSUE THREAD

**Issue by henrikp** [trillek-team/tec#166]
Gentoo, unstable amd64. https://github.com/trillek-team/tec/commit/1faa755671a275acae4d9aea4bb3e165c34940d6 updated the path for spdlog's `pattern_formatter.h` into `spdlog/details` but actually the file is located directly in `spdlog`. Modifying the path in `client/gui/console.hpp` allows the components to build. Now to find that 1000.json ...

**Comment by adam4813** [comment]
Thanks for reporting, lucky for you the PR that I am about to merge fixes this https://github.com/trillek-team/tec/pull/165/files#diff-82d748f2a2dd8bdf4be66a04dc310831R12 . 1000.json is in the assets sub-module json folder
