### ISSUE TITLE
Lua API needed

### ISSUE THREAD

**Issue by adam4813** [trillek-team/tec#17]
The following items need to be exposed to the scripting system in the form of an API, once a scripting system is integrated.
- [ ] Play, Pause, Stop audio
- [ ] Entity interface
- [ ] Edit Velocity
- [ ] Edit Transforms (position, orientation, scale)
- [ ] Event listeners

**Comment by milesrout** [comment]
For the sake of avoiding discussion on the relatively trivial issue of language choice, we should go with what has been decided already for previous iterations of the engine: Lua. It's designed for exactly this sort of thing, has shown time and time again in the real world that it works well, and crucially is something we've already discussed and agreed on.

**Comment by adam4813** [comment]
Updated issue name to match your comment.

**Comment by milesrout** [comment]
@adam4813 no work on this yet?

**Comment by Zardoz89** [comment]
I just begin with it : https://github.com/Zardoz89/tec/tree/lua_selene

**Comment by milesrout** [comment]
:+1:

**Comment by Zardoz89** [comment]
Actually I have a minimal setup working : 

- Linking against Lua on Windows and Linux
- Reading a Lua script and reading Lua vars from Lua state

Now is the time of implement a basic LuaComponent and a LuaSystem where LuaComponent stores 3 optional scripts : 
  - init script -> Executed when the entity is created and put on the world/scene
  - update script -> Executed every game loop iteration
  - terminate script -> Executed when the entity would be removed from the world/scene

If these scripts are changed when the engine is running, I think that should reloaded. Perhaps a  I simple call LuaState.Load(script) to be re-parsed.

*Doubts*
 - LuaComponent could store a instance of LuaState or should have a LuaState on LuaSystem were all scripts run ???

**Comment by adam4813** [comment]
Component might be a good place for state so each entity could have its own
state.

**Comment by Zardoz89** [comment]
I thought the same, plus it would allow to run Lua scripts for each entity on a concurrent way.

**Comment by Zardoz89** [comment]
Status : 
 - Minimal working implementation of LuaSystem , LuaScript and ScriptFile (System, Component, Resource)
 - Hello world from Lua working 
![image](https://cloud.githubusercontent.com/assets/888483/10438053/6e021b72-7131-11e5-8c79-ccca6f06a21a.png)
- Actually it depends from a fork of Selene that implements a ```LoadStr(std::string& script)```. PR to Selene repository send to merge this. If this PR comes approved quickly, I would update my TEC fork with all.

TODO : 
- Expose``` entity[entity_id]``` object (```this``` parameter on lua function **onUpdate** & cia ) and Entity class.
- Find a way of overwrite lua print function by one that uses our logger/console
- Expose more TEC API to lua.
- Find were and how we should call **onInit** and **onDestroy** lua functions

**Comment by Zardoz89** [comment]
Also, I paste here a link about embed Lua sandboxing : http://stackoverflow.com/questions/1224708/how-can-i-create-a-secure-lua-sandbox

This would be necessary, mainly if we not like that someone try to mess server side files with a harmful lua script

**Comment by adam4813** [comment]
https://app.clickup.com/2261801/v/li/6201851

**Comment by milesrout** [comment]
?

**Comment by adam4813** [comment]
@milesrout sent you an email not sure if you got it

**Comment by adam4813** [comment]
I have started created a document to describe the API https://github.com/trillek-team/tec/wiki/API-Documentation. I am going to close this ticket in favor of move specific issues.

**Comment by adam4813** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Lua API](https://trello.com/c/Fm0YR8ns/6-lua-api)
