### ISSUE TITLE
Expose certain APIs to Lua

### ISSUE THREAD

**Issue by dimaguy** [trillek-team/tec#184]
I'd like these events to be exposed to lua:

- [X] Commands/Chat (with name of player or other identifier)
- [x] Player Join (with IP and identifier)
- [ ] Player Interaction with objects like computers (with identifier and entity id + type of interaction)
- [ ] Player Movement (with identifier and data useful to movement)
- [x] Player Leaving (with identifier)

I'd like events 1 to 4 to be cancellable.

I'd like these calls to be exposed to lua:

- [ ] Teleport
- [ ] Kick
- [x] PlayerInfo(which provides a table with any Info of the requested player)
- [x] List of Players
- [ ] Entity Spawning

**Comment by adam4813** [comment]
Added 0.2 milestone as there is some underlying architecture needed for a few of these. Some might might be able to be done sooner.

**Comment by adam4813** [comment]
onChatCommand has been added see api docs

**Comment by adam4813** [comment]
Player info and player list are exposed via User and UserList. Currently the only data is the user's Id and their username. If you can expand on what data you'd like for a user please note it somewhere.

**Comment by adam4813** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Lua API](https://trello.com/c/Fm0YR8ns/6-lua-api)

**Comment by adam4813** [comment]
- Player Movement (with identifier and data useful to movement) **not implemented as this isn't an event at this time**
