### ISSUE TITLE
Second computer screen blank on OSX

### ISSUE THREAD

**Issue by blexaer** [trillek-team/tec#192]
**Describe the bug**
The computer to the left appears with a black screen. Keyboard input is not visible as on windows build.

**To Reproduce**
Build and run on OSX. Observe the left computer.

**Comment by Meisaka** [comment]
The computer on the left is entity 101, and is technically the first of the two.
Debugging this a bit, one of the glDrawElements calls in RenderSystem::BeginPointLightPass() raises an illegal operation error,
a glGetError() check doesn't happen until the beginning of the texture's Load() method.
The texture Load method wrongly bails out early after reading the failed render pass' error code.
[See render-system.cpp for the offending line](https://github.com/trillek-team/tec/blob/8456e09754881ed70b3d5d2cd8749ab8bf64c687/client/render-system.cpp#L267)
