### ISSUE TITLE
Fix unneeded loading of dynamic libraries on the client macOS

### ISSUE THREAD

**Issue by blexaer** [trillek-team/tec#213]
**Describe the bug**
I have a environment variable DYLD_LIBRARY_PATH set to a location. This for some unknown reason gets loaded by the client.

**To Reproduce**
Set DYLD_LIBRARY_PATH to any folder containing a .dylib file.

**Expected behavior**
Nothing

**Comment by Meisaka** [comment]
Worked fine for me on 10.12.6 using a generic path: https://i.imgur.com/qNjsuvo.png
Perhaps it's something more specific?

**Comment by blexaer** [comment]
what about two paths separated by a color
$path:/usr/lib:$another_path

**Comment by blexaer** [comment]
Specific path in question is:
export DYLD_LIBRARY_PATH="/usr/local/opt/sqlite/lib:/usr/lib:$DYLD_LIBRARY_PATH

**Comment by Meisaka** [comment]
I tried setting the sqlite path specifically, after confirming that it exists and has dylibs in it.
it does not seem limited to tec specifically, and could be a bug with sqlite:
![dylib2](https://user-images.githubusercontent.com/5482813/112072982-0e100c80-8b41-11eb-830d-3abb2268f675.png)

**Comment by blexaer** [comment]
After checking libs on the client, the likely cause is probably the cocoa framework which uses sqlite.
Closing issue as it has nothing to do with tec.
