### ISSUE TITLE
tec::EventQueue needs virtual destructor

### ISSUE THREAD

**Issue by ralian** [trillek-team/tec#22]
In specific dynamic implementations, tec::EventQueue might be stored and freed by anonymous superclass references, resulting in a memory leak unless tec::EventQueue::~EventQueue is made virtual.

**Comment by milesrout** [comment]
If a class is intended to be inherited and used polymorphically, then it should have a virtual destructor.  
If a class is intended to be inherited but not to be used polymorphically, then it should not have a virtual destructor.  
If a class is not intended to be inherited, it should be `final`. e.g.

    struct A final {};
    struct B : A {}; // error

**Comment by ralian** [comment]
Yes, EventQueue very well could be used polymorphically.

**Comment by adam4813** [comment]
EverntQueue is in fact used polymorphically via the ProcessEventQueue
method.

On Sun, Jun 28, 2015 at 9:04 PM, William Bowers <notifications@github.com>
wrote:

> Yes, EventQueue very well could be used polymorphically.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/trillek-team/tec/issues/22#issuecomment-116375756>.
>



-- 
-Adam
