### ISSUE TITLE
Centralize RegisterLuaType calls from server/main.cpp into LuaSystem

### ISSUE THREAD

**Issue by adam4813** [trillek-team/tec#222]
https://github.com/trillek-team/tec/blob/54682c7c62c6840e049ee203f60f2652e3d28afd/server/main.cpp#L79-L82

**Comment by blexaer** [comment]
A solution might be passing a lambda function to the lua system that registers the needed data types. 
Doing so in the contructor of the systems that want to register data types would be best if possible, as we this way get rid of the function calls from main.cpp

**Comment by blexaer** [comment]
Another solution would be to register a callback function in the LuaSystem when the system is constructed, later calling the registered function when the data is ready to expose
