### ISSUE TITLE
OpenAL

### ISSUE THREAD

**Issue by adam4813** [trillek-team/tec#3]

**Comment by Zardoz89** [comment]
What do you think about this lib ? https://github.com/camlorn/libaudioverse

It uses OpenAL under the hood, but implements 3d audio and audio synth (and it's supposed to be fast), so we could shoot two birds with a single bullet.

**Comment by adam4813** [comment]
Looks promising, but under building it reads "Currently Libaudioverse only
builds on Windows. This is a restriction that I intend to lift by the end
of May. Libaudioverse itself will build fine on other platforms, but the
build scripts don't know how to handle it and Libaudioverse is currently
missing audio backends. If you are on Linux or Mac, watch this space" and
it requires python which isn't a deal breaker but the goal is to reduce
dependancies and simplify the build process.
