### ISSUE TITLE
Find assets folder and user configuration 

### ISSUE THREAD

**Issue by adam4813** [trillek-team/tec#30]
We need a way of finding game assets and user configuration regardless of executable location and run directory.

**Comment by Zardoz89** [comment]
On unix, a program usually are installed on this way :
binaries files (executables) : /usr/bin/
Assets/Resources (read only): /usr/share/AppName/
System config files (for example server config): /etc/AppName or /etc/AppName/ .
User setting files : /home/MyUser/.config/AppName/
Docs : /usr/share/doc/AppName/

But there is other variations :
If the program is being installed by hand/script, not using a package manager

Way 1 on /usr/local/ :
binaries files (executables) : /usr/local/bin/
assets/resources : /usr/local/share/AppName/
Docs : /usr/local/share/doc/AppName/

Way 2 on /opt/ :
binaries files (executables) : /opt/AppName/bin/
assets/resources and all other stuff: /opt/AppName/

Way 3 on a folder on home (rare):
binaries files (executables) : /home/MyUser/AppName/bin/
assets/resources : /home/MyUser/AppName/
Docs : /home/MyUser/AppnName/doc/

Way 4 using /usr/games/ (Very rarre) :
binaries files (executables) : /usr/share/games/AppName/bin
assets/resources : /usr/share/games/AppName/
Docs : /usr/share/games/AppName/doc/

The Way 1 is the default paths used by package managers. Way 2 is the usual when you compile and install from source code. Way 3 is used by freak programs like Oracle, Chrome, etc. Way 4, I only see Zandronum and VCMI using it.

Locating the user settings file is pretty easy. Getting read-only assets/resources is more problematic but could be archived doing a multi-step try with the different default locations. Also there is a few environment vars that should indicate the default paths.
The step procedure would be (XXX being the resource/assets relative path): 

1. Try relative to the path from where the program is being executed (ie, try ./XXX )
2. Get program binary location (I call $EXE ) and : 
  1. Try $EXE/../share/AppName/XXX
  2. Try $EXE/XXX

The first time, the base path to resources is stored on a static var, so isn't necessary repeat the whole process every time

This procedure also could work on Windows if we keep the binary file on a /bin subdir on install
On OSX I don't know the default paths, but assuming that we not install using Apple Store, should be the same paths that any other unix system.

For cache files dir, we can relay enviroment vars and OS AI to get it.

Some usefull tricks and Windows & OSX and env vars could be see on action here : https://github.com/Malvineous/cfgpath/blob/master/cfgpath.h

How get the program binary location : http://stackoverflow.com/questions/933850/how-to-find-the-location-of-the-executable-in-c

**Comment by Zardoz89** [comment]
Ok, this is resolved on PR #45
