### ISSUE TITLE
Entity world placing

### ISSUE THREAD

**Issue by adam4813** [trillek-team/tec#35]
This involves the ability for a player to add, move, and remove entities to the world.

For this, engine systems will need to handle mouse click events and take appropriate action. Also editing widgets such as a rotation arc ball and translation cross-hair will need to be added as well.

- [x] Determine mouse click location within world
- [x] Create new entity at given location with selected properties
- [ ] Add collision check for valid placement
- [ ] Add shader to indicate valid placement

**Comment by adam4813** [comment]
Related #33 Material Picker.

**Comment by milesrout** [comment]
Definitely doesn't need to be in 0.1.

**Comment by milesrout** [comment]
Accidentally moved to 0.12, moved it back.

**Comment by adam4813** [comment]
Migrating this issue to being able to place an airlock in the world to serve as a starting point for creating ships. This provides a way to "connect" walls, floors, etc within the game world.
