### ISSUE TITLE
Implement network system using ASIO

### ISSUE THREAD

**Issue by adam4813** [trillek-team/tec#4]

**Comment by milesrout** [comment]
So, what's the goal here? To evaluate ASIO for use in the engine, or to use ASIO in the engine? Perhaps 'Implement networking system' would be a better ticket name.

**Comment by adam4813** [comment]
Updated title to match your suggestion.

**Comment by Zardoz89** [comment]
Using this https://think-async.com/ I understand, not ?

**Comment by adam4813** [comment]
Yes. I have the ground work already done locally.

**Comment by adam4813** [comment]
http://stackoverflow.com/questions/10954392/reading-protobuf-objects-using-boostasioread-async for me to reference with using protobuf. This also ties into issue #5 Component Streaming using protobufs.

**Comment by milesrout** [comment]
@adam4813 Status of this ticket?

**Comment by adam4813** [comment]
I will get on it now, just for you.

**Comment by adam4813** [comment]
This is fairly complete and just needs tweaking so I'm going to close this issue and make separate issues for any tweaks needed.
