### ISSUE TITLE
Default PixelBuffer/Texture

### ISSUE THREAD

**Issue by Zardoz89** [trillek-team/tec#42]
Add a default embed PixelBuffer and Texture, so the engine not crash if there is a missing texture. The default texture could be a checker texture like : https://svn.ict.usc.edu/svn_vh_public/trunk/lib/OgreSDK/media/materials/textures/checker.png or something like this : ![DooMBuilder missing texture](http://i35.photobucket.com/albums/d155/evanmontegarde/dbeditor.jpg)

Could be (Pseudocode) : 

On RenderSystem subsystem init : 
```
...
{
  std::uint8_t tmp_buff = {
    #include "default_texture.hpp" // Carmack's trick . Contains a 128x128x1 bytes of monocrome texture data
  };
  PixelBuffer default_pbuffer(128, 128, 8, ImageColorMode::MONOCHROME );
  std::copy_n(tmp_buff, sizeof(tmp_buff), default_pbuffer.LockWrite());
  default_pbuffer.UnlockWrite()
  PixelBufferMap.Default(default_pbuffer);

  TextureObject default_texture(PixelBufferMap.Default());
  TextureMap.Default(default_texture);
}
...
```

**Comment by adam4813** [comment]
@Zardoz89 any chance you've had a chance to do this?

**Comment by Zardoz89** [comment]
I don't update  my local copy for some time. I could try, but I can't promise anything. I had very few time this lasts months (stuff related to my father health, and I was a bit depressed )

**Comment by adam4813** [comment]
It is fine family and life above all. Travis reports the build is nearly
good code wise so it shouldn't be too bad.

**Comment by adam4813** [comment]
Ok implemented in my fork.
