### ISSUE TITLE
Global systems container

### ISSUE THREAD

**Issue by Zardoz89** [trillek-team/tec#43]
Actually we are creating all system object on the main and we not are storing it on any place. So if for example another system need to access another system (for example, the whole gui that now are on the main.cpp, could be his own system, and be a editor-gui-system, but need to access to imgui-system), could access this container.

For example on main, we could have a pre-game loop code like : 
```
SystemContainer.init();
SystemContainer.addSystem("os", tec::OS os);
SystemContainer.addSystem("gui",  tec::IMGUISystem gui( ((tec::OS)SystemContainer["os"]).GetWindow());
...
```

Perhaps we could implement it using multitone and with a ASystem abstract base class for all systems.

**Comment by adam4813** [comment]
I think the only thing that needs access to other systems would be gui and
scripting. We should try to isolate each system as best as possible.
