### ISSUE TITLE
Component streaming

### ISSUE THREAD

**Issue by adam4813** [trillek-team/tec#5]
For this is work entity class will need a static map for out stream lambdas for each added component. The lambda should take a stream and will allow type erasure so all lambdas can be stored in the same map.
````
std::map<eid, [] (stream) {}> component_out_streams; // Potential signature
````

**Comment by milesrout** [comment]
Lambdas have an anonymous type. But they can be stored in a `std::function` (as can all other callable objects) which uses type erasure. So most likely we would want:

    std::unordered_map<eid, std::function<F>> component_out_streams;

**Comment by adam4813** [comment]
Yeah that's kind of what I have in a local branch.

**Comment by milesrout** [comment]
>The lambda should take a stream and will allow type erasure so all lambdas can be stored in the same map.

The overhead of `std::function` is just the normal overhead incurred with all type erasure.

**Comment by adam4813** [comment]
https://github.com/google/protobuf/tree/master/cmake under Compiling and Installing step 2 -DBUILD_TESTING=OFF needs to be enforced in our cmake.
