### ISSUE TITLE
Massive use of shared_ptr

### ISSUE THREAD

**Issue by N1xx1** [trillek-team/tec#65]
Not sure if this project is still active, but going to give my 2 cents anyway.

I know how a programmer feels about C++11, great amazing stuff introduced, better ways of developing software and stuff, but often you don't need those features. Let's say we have a Multiton (not that I like this patter in this context) as a global variable, using a shared_ptr inside it's bad. That's because the map (I don't see any reason to not use unordered_map, tbh) will always own it and even if all other pointers to it are freed the resource won't get freed. This makes the reference count a useless overhead.

The best solution, I think, is to just use a owning ptr, i.e. unique_ptr, and pass around non owning ptr, i.e. raw pointers (or references if you really don't like them).

Or if you feel so you can use weak_ptrs and a custom deallocator (you have to remove weak_ptrs from the map when they aren't needed anymore), but still think about who'll own the memory.

**Comment by adam4813** [comment]
I concur about the use of shared_ptr. It was mainly used to maintain life
cycle, but the order of events (modifying component state) was defined
after the design choice and made it unnecessary.

What I'm saying is that I am reducing the use of smart pointers with each
commit ;) and hope to use unique or raw as much as possible.

**Comment by adam4813** [comment]
Ok I think I did it.

As there isn't a real quantifiable way of saying how many is good or bad I am going to close this issue to clean up the issues some. Just know that changes being pushed in the next day or 2 will correct this issue in part or in whole.
