### ISSUE TITLE
Atmosphere system

### ISSUE THREAD

**Issue by adam4813** [trillek-team/tec#72]
A system (could be done in scripting) that dictates the level of oxygen, temperature, etc of a given region. The system would iterate over all entities within its region and modify that entity's vital component to adjust its corresponding stat. E.g if the O2 goes down in the room the entity's vital component O2 stat would decrease.

**Comment by dangranos** [comment]
It would be nice, if this system wasn't just "no O2" and "have 02" but had actual pressure and also included at least CO2, which would be generated or consumed by appropriate entities. Maybe with addition of some kind of pipe system?

**Comment by adam4813** [comment]
Cleaning up issues and might revisit, but no longer relevant
