### ISSUE TITLE
OS X Support + CI

### ISSUE THREAD

**Issue by milesrout** [trillek-team/tec#81]
Support for building and running on OS X, instructions for building and running on OS X, and continuous integration (on travis.ci?) for the OS X build.

**Comment by adam4813** [comment]
Travis can do osx and clang is now good, so maybe it can be enabled now?

Or at the least maybe it can be assumed if Travis's clang build works that
it will at least compile on osx?

**Comment by milesrout** [comment]
The changes needed for this basically come down to the code being written (actually rather well) for OS X but clearly not actually compiled on OS X.

So I don't have much porting to do, mostly just fixing a few syntax errors, fixing some build system problems, some OpenGL header and linking issues, the usual OS X stuff.

**Comment by adam4813** [comment]
Win, getting an OS X build out too would be very much a step forward.

>

-- 
-Adam
