### ISSUE TITLE
Client performance is very low

### ISSUE THREAD

**Issue by jmf** [trillek-team/tec#83]
Currently the client uses a lot of CPU power without doing much.
On my system, it uses 100% of one CPU thread.
This is inconvenient especially for mobile systems with batteries, where economical CPU usage matters.

**Comment by Xellon** [comment]
![image](https://cloud.githubusercontent.com/assets/19504901/17221725/a0d9dbb0-54fd-11e6-890d-14a1e63e965d.png)

Maybe it can help

**Comment by adam4813** [comment]
I found a case of it rendering every mesh part every texture for no reason....perhaps this is resolved now so moving this to closed hoping we can get a more detailed reason in a more focused ticket.
