### ISSUE TITLE
Create proper CMake subprojects

### ISSUE THREAD

**Issue by danielekmann** [trillek-team/tec#88]
Right now the `src` directory still contains things specific to the client only, and the build system is very monolithic with one central `CMakeLists.txt` file in the root directory. We should move the remaining client-specific code to `client/`, and create `client/CMakeLists.txt` and `server/CMakeLists.txt` files that take care of building only the client or the server, respectively.

**Comment by milesrout** [comment]
If we're going to have the client and server code in one repository we could at least have them in separate directories with the common code in a third.

e.g. https://github.com/freebsd/freebsd

There's a global freebsd makefile that makes all of freebsd. We can still have that, the ability to make everything in one go. But we should split the code up.

**Comment by adam4813** [comment]
I already moved most of the client and server specific code to their
respective folder. I am not saying I got it all, but 90%.

**Comment by adam4813** [comment]
The latest commits accomplishes this i believe.
