### ISSUE TITLE
Shouldn't have to change every single file to change the copyright year

### ISSUE THREAD

**Issue by milesrout** [trillek-team/tec#89]
Before 2017, it would be nice to get explicit years out of each individual file. It creates messy difficult to understand history to update every file in the repository. 

Yearly commit should look like this: https://github.com/freebsd/freebsd/commit/0219f2b937baf6515d4cd2bf7311adfbdfef2e20
Not like this: https://github.com/trillek-team/tec/commit/66d407454bbf1ed52fcf3e0ad1375e34671a6626

**Comment by milesrout** [comment]
"Before 2017" ahaha

Might as well do this before 2020.

**Comment by adam4813** [comment]
Ha!!

**Comment by adam4813** [comment]
Jokes on me....
