### ISSUE TITLE
Delta component updates

### ISSUE THREAD

**Issue by adam4813** [trillek-team/tec#9]
Instead of just assigning the component to the new value, only data that was changed should be updated. This will prevent loss of state and reduce object creation.

Entity::Update() could take a bitset saying what data was updated and passing that to the component in some useful way. This might require components to provide an update function in the form of a lambda.

**Comment by milesrout** [comment]
This is an optimisation, so probably doesn't need to happen until 0.2.

**Comment by adam4813** [comment]
Will revisit later
