### ISSUE TITLE
Autogenerated files shouldn't be in the repository

### ISSUE THREAD

**Issue by milesrout** [trillek-team/tec#90]
Unless they're very slow to generate and quite small or something, anyway.

**Comment by danielekmann** [comment]
Particularly refers to protobuf's `.pb.cc`/`.pb.h` files.

**Comment by adam4813** [comment]
I added those (pb.cc) as they aren't auto generated by the actual engine
they are compiled via protoc externally and are not generated often. For
example that is only the first or second iteration in the repo after all
these months.

**Comment by milesrout** [comment]
They can be generated by the normal engine process.

**Comment by danielekmann** [comment]
Here is what it takes to fix this issue:
```
find_package(Protobuf REQUIRED)
protobuf_generate_cpp(COMPONENTS_SOURCES COMPONENTS_HEADERS ${trillek-common_SOURCE_DIR}/proto/components.proto)
protobuf_generate_cpp(GAME_STATE_SOURCES GAME_STATE_HEADERS ${trillek-common_SOURCE_DIR}/proto/game_state.proto)
```
Not closing this until the reworked build system is merged, though.

**Comment by adam4813** [comment]
The latest commits add @danielekmann changes.
