### ISSUE TITLE
Upside down view after connecting to server

### ISSUE THREAD

**Issue by Xellon** [trillek-team/tec#91]
![image](https://cloud.githubusercontent.com/assets/19504901/15797908/bea03dae-2a2f-11e6-8d16-ce76fd8f6040.png)

When I connected to the server, view got turned upside down, with mouse movements to left and right being inverted.
Out of 5 times it happened once.

**Comment by adam4813** [comment]
This is a glitch that happens rarely with the camera being interpolated
wrong from the initial data sent from the server. To correct until fixed
just connect again until you are upright.

**Comment by adam4813** [comment]
My latest PR bandages this to explicitly set your orientation to be upright, but this does need to be reworked as part of the bigger rework process, so closing for now.
