### ISSUE TITLE
Exponential movement slowdown

### ISSUE THREAD

**Issue by Xellon** [trillek-team/tec#92]
After moving a certain amount of distance (and/or possibly time), player starts slowing down and almost stops, but then jumps back again after triple stutter.

Edit. Velocity seems to stay the same = 7, so maybe it's server problem ?
Also found another bug if you press D to move right, then pressing A before releasing D will result in a pause right after releasing D; same with W and S.

**Comment by adam4813** [comment]
This might be fixed now with the latest changes. @Xellon if you're feeling it care to double check. If not I think we can close this issue end of the month as it is fairly stale at this point.

**Comment by Xellon** [comment]
This seems to be fixed, but the movement is awful now: stuttering and input delay (maybe inertia too strong).

**Comment by adam4813** [comment]
That is a different issue and something that is on my mind to fix. Right now it sends movement to the server, but doesn't start moving until the server says move.
