### ISSUE TITLE
OS X Instructions + CI

### ISSUE THREAD

**Issue by milesrout** [trillek-team/tec#96]
We should have a continuous integration build on travis.ci for the OS X build and instructions in the README.

**Comment by milesrout** [comment]
I think it requires quite a few deep changes to separate out frame-buffer vs. window sizes which is necessary both for proper retina display support.

**Comment by adam4813** [comment]
Umm wrong comment on this issue maybe?

**Comment by milesrout** [comment]
well kind of, but my macbook was the first time I have used Trillek on a retina display and it did not go well

**Comment by adam4813** [comment]
Looks like the CI can be accomplished via github actions!

**Comment by adam4813** [comment]
Fixed CI with the usage of github actions!
