### ISSUE TITLE
There are too many warnings during the build.

### ISSUE THREAD

**Issue by milesrout** [trillek-team/tec#97]
Most of these are fairly harmless and can be fixed with a few scattered `static_cast<>`s, but some might be more serious and it's hard to tell when there's so many of them.

**Comment by adam4813** [comment]
Can you list some so we can tackle them?

**Comment by milesrout** [comment]
In quite a few places there are errors about enumeration values not being handled. I will look a bit more carefully at them but from a quick glance it seems like there are switches that don't handle all the possible components but just a small subset of them. "13 enumeration values not handled in switch: 'COMPONENT_NOT_SET', 'kRenderable', 'kView', ... [-Wswitch]" is a hefty chunk of the warnings on my computer.

On appveyor, there are some issues with functions not being properly marked as exported from DLLs (or something like that) that fill up the log when protobuf is being built.

**Comment by adam4813** [comment]
OK I'll most likely just package up protobuf so it doesn't build it saving
a large amount of the build.

**Comment by milesrout** [comment]
https://gist.github.com/milesrout/2517a391d47de42e169f9826fc555a84

List of the warnings I get when I build locally, excluding linker warnings from Bullet about building for OS X 10.7 on 10.11.

**Comment by adam4813** [comment]
@milesrout fixed a bunch more in the latest PR. I am going to close this in favor of more specific tickets now that 90% (just a guess) of warnings are gone.
